/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/rfq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Rfq */
        put: operations["save_rfq_sessions__session_id__rfq_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/rubric/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Rubric */
        post: operations["generate_rubric_sessions__session_id__rubric_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/rubric": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Save Rubric */
        patch: operations["save_rubric_sessions__session_id__rubric_patch"];
        trace?: never;
    };
    "/sessions/{session_id}/rubric/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock Rubric */
        post: operations["lock_rubric_sessions__session_id__rubric_lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_sessions__session_id__artifact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BuyerPriority */
        BuyerPriority: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Session Id */
            session_id?: string | null;
        };
        /** Criterion */
        Criterion: {
            /** Id */
            id: string;
            /** Section Id */
            section_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            criterion_type: components["schemas"]["CriterionType"];
            /** Weight */
            weight?: number | null;
            /** Min Cutoff */
            min_cutoff?: number | null;
            /** Max Score */
            max_score?: number | null;
            /** Evidence Checks */
            evidence_checks?: components["schemas"]["EvidenceCheck"][];
            /** Linked Question Ids */
            linked_question_ids?: string[];
            /** Linked Schedule Fields */
            linked_schedule_fields?: string[];
        };
        /**
         * CriterionType
         * @enum {string}
         */
        CriterionType: "mac" | "technical_cutoff_backed" | "technical_scored_only" | "commercial";
        /** DownloadMetadata */
        DownloadMetadata: {
            /** File Name */
            file_name: string;
            /**
             * Content Type
             * @default application/json
             */
            content_type: string;
        };
        /** EvidenceCheck */
        EvidenceCheck: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
        };
        /** GeneralInfo */
        GeneralInfo: {
            /** Title */
            title: string;
            /** Rfq Code */
            rfq_code: string;
            /** Owner */
            owner: string;
            /** Region */
            region: string;
        };
        /** GovernanceInfo */
        GovernanceInfo: {
            /**
             * Official Award Basis
             * @default QCBS 70/30
             * @constant
             */
            official_award_basis: "QCBS 70/30";
            /** Technical Threshold Strategy */
            technical_threshold_strategy: string;
            /** Advisory Outputs */
            advisory_outputs: string[];
            /** Persistence Scope */
            persistence_scope: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LineItem */
        LineItem: {
            /** Id */
            id: string;
            /** Product Name */
            product_name: string;
            /** Category */
            category: string;
            /** Description */
            description: string;
            /** Hsn Sac */
            hsn_sac: string;
            /** Uom */
            uom: string;
        };
        /** LockedFrameworkArtifact */
        LockedFrameworkArtifact: {
            /**
             * Version
             * @default 1.0
             */
            version: string;
            /**
             * Locked At
             * Format: date-time
             */
            locked_at: string;
            rfq_snapshot: components["schemas"]["RFQDraft"];
            rubric_snapshot: components["schemas"]["RubricProposal-Output"];
            governance: components["schemas"]["GovernanceInfo"];
            download_metadata: components["schemas"]["DownloadMetadata"];
        };
        /** Question */
        Question: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Purpose */
            purpose: string;
            /** Linked Criteria */
            linked_criteria?: string[];
        };
        /** RFQDraft */
        RFQDraft: {
            general_info: components["schemas"]["GeneralInfo"];
            /** Scope Overview */
            scope_overview: string;
            /** Timelines */
            timelines: components["schemas"]["TimelineItem"][];
            /** Buyer Priorities */
            buyer_priorities: components["schemas"]["BuyerPriority"][];
            /** Mandatory Conditions */
            mandatory_conditions: string[];
            /** Line Items */
            line_items: components["schemas"]["LineItem"][];
        };
        /** ResponseSchedule */
        ResponseSchedule: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Purpose */
            purpose: string;
            /** Columns */
            columns: components["schemas"]["ScheduleColumn"][];
            /** Linked Criteria */
            linked_criteria?: string[];
        };
        /** RubricProposal */
        "RubricProposal-Input": {
            /** Sections */
            sections: components["schemas"]["RubricSection"][];
            /** Criteria */
            criteria: components["schemas"]["Criterion"][];
            /** Aggregate Technical Threshold */
            aggregate_technical_threshold: number;
            /** Questions */
            questions: components["schemas"]["Question"][];
            /** Response Schedules */
            response_schedules: components["schemas"]["ResponseSchedule"][];
            /**
             * Official Award Basis
             * @default QCBS 70/30
             * @constant
             */
            official_award_basis: "QCBS 70/30";
            /** Generation Rationale */
            generation_rationale: string[];
        };
        /** RubricProposal */
        "RubricProposal-Output": {
            /** Sections */
            sections: components["schemas"]["RubricSection"][];
            /** Criteria */
            criteria: components["schemas"]["Criterion"][];
            /** Aggregate Technical Threshold */
            aggregate_technical_threshold: number;
            /** Questions */
            questions: components["schemas"]["Question"][];
            /** Response Schedules */
            response_schedules: components["schemas"]["ResponseSchedule"][];
            /**
             * Official Award Basis
             * @default QCBS 70/30
             * @constant
             */
            official_award_basis: "QCBS 70/30";
            /** Generation Rationale */
            generation_rationale: string[];
        };
        /** RubricSection */
        RubricSection: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
        };
        /** ScheduleColumn */
        ScheduleColumn: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /**
             * Required
             * @default true
             */
            required: boolean;
        };
        /** SessionSnapshot */
        SessionSnapshot: {
            /** Session Id */
            session_id: string;
            status: components["schemas"]["SessionStatus"];
            rfq_draft: components["schemas"]["RFQDraft"];
            rubric_proposal?: components["schemas"]["RubricProposal-Output"] | null;
            locked_artifact?: components["schemas"]["LockedFrameworkArtifact"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "draft" | "proposal_ready" | "locked";
        /** TimelineItem */
        TimelineItem: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Target Date */
            target_date: string;
            /** Description */
            description: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_rfq_sessions__session_id__rfq_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RFQDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_rubric_sessions__session_id__rubric_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_rubric_sessions__session_id__rubric_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RubricProposal-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_rubric_sessions__session_id__rubric_lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockedFrameworkArtifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_sessions__session_id__artifact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
