/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/rfq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Rfq */
        put: operations["save_rfq_sessions__session_id__rfq_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/rubric/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Rubric */
        post: operations["generate_rubric_sessions__session_id__rubric_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/rubric": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Save Rubric */
        patch: operations["save_rubric_sessions__session_id__rubric_patch"];
        trace?: never;
    };
    "/sessions/{session_id}/rubric/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock Rubric */
        post: operations["lock_rubric_sessions__session_id__rubric_lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_sessions__session_id__artifact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/vendor-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vendor Pack */
        get: operations["get_vendor_pack_sessions__session_id__vendor_pack_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/vendor-pack/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Vendor Pack */
        get: operations["export_vendor_pack_sessions__session_id__vendor_pack_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Vendor */
        post: operations["create_vendor_sessions__session_id__vendors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/vendors/{vendor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Vendor */
        delete: operations["delete_vendor_sessions__session_id__vendors__vendor_id__delete"];
        options?: never;
        head?: never;
        /** Update Vendor */
        patch: operations["update_vendor_sessions__session_id__vendors__vendor_id__patch"];
        trace?: never;
    };
    "/sessions/{session_id}/vendors/{vendor_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload Vendor Document */
        put: operations["upload_vendor_document_sessions__session_id__vendors__vendor_id__document_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/vendors/{vendor_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Vendor Document */
        post: operations["extract_vendor_document_sessions__session_id__vendors__vendor_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/vendors/{vendor_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vendor Review */
        get: operations["get_vendor_review_sessions__session_id__vendors__vendor_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/comparison-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Comparison Settings */
        put: operations["save_comparison_settings_sessions__session_id__comparison_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/evaluation/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Session Evaluation */
        post: operations["run_session_evaluation_sessions__session_id__evaluation_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Results */
        get: operations["get_results_sessions__session_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AwardRecommendation */
        AwardRecommendation: {
            /** Winner Vendor Id */
            winner_vendor_id?: string | null;
            /** @default single_vendor */
            award_type: components["schemas"]["AwardType"];
            /** Eligible Vendor Ids */
            eligible_vendor_ids?: string[];
            /** Score Breakdown */
            score_breakdown?: components["schemas"]["VendorScoreBreakdown"][];
            /** Evidence Refs */
            evidence_refs?: string[];
            /** Explanation */
            explanation: string;
            /** Risks */
            risks?: string[];
        };
        /**
         * AwardType
         * @enum {string}
         */
        AwardType: "single_vendor" | "split_award";
        /** Body_upload_vendor_document_sessions__session_id__vendors__vendor_id__document_put */
        Body_upload_vendor_document_sessions__session_id__vendors__vendor_id__document_put: {
            /** File */
            file: string;
        };
        /** BuyerPriority */
        BuyerPriority: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
        };
        /** CommercialEvaluationResult */
        CommercialEvaluationResult: {
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name: string;
            /** Eligible For Commercial */
            eligible_for_commercial: boolean;
            /** Award Ready */
            award_ready: boolean;
            /** Base Currency */
            base_currency: string;
            /** Comparable Total */
            comparable_total?: number | null;
            /** Commercial Score */
            commercial_score?: number | null;
            /** Line Items */
            line_items?: components["schemas"]["CommercialLineItemResult"][];
            /** Anomalies */
            anomalies?: string[];
            /** Blockers */
            blockers?: string[];
            /** Explanation */
            explanation: string;
            /** Evidence Refs */
            evidence_refs?: string[];
        };
        /** CommercialLineItemResult */
        CommercialLineItemResult: {
            /** Line Item Id */
            line_item_id: string;
            /** Line Item Name */
            line_item_name: string;
            /** Base Currency Total */
            base_currency_total?: number | null;
            comparability_status: components["schemas"]["ComparabilityStatus"];
            /** Notes */
            notes?: string[];
        };
        /**
         * ComparabilityStatus
         * @enum {string}
         */
        ComparabilityStatus: "comparable" | "needs_buyer_input" | "non_comparable" | "informational";
        /** ComparisonSettings */
        ComparisonSettings: {
            /** Base Currency */
            base_currency: string;
            /** Fx Effective Date */
            fx_effective_date: string;
            /** Fx Rates */
            fx_rates?: components["schemas"]["FXRate"][];
            /** Uom Overrides */
            uom_overrides?: components["schemas"]["UomOverride"][];
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Session Id */
            session_id?: string | null;
        };
        /** CreateVendorRequest */
        CreateVendorRequest: {
            /** Name */
            name: string;
        };
        /** Criterion */
        "Criterion-Input": {
            /** Id */
            id: string;
            /** Section Id */
            section_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            criterion_type: components["schemas"]["CriterionType"];
            /** Weight */
            weight?: number | null;
            /** Min Cutoff */
            min_cutoff?: number | null;
            /** Max Score */
            max_score?: number | null;
            /** Evidence Checks */
            evidence_checks?: components["schemas"]["EvidenceCheck"][];
            /** Linked Question Ids */
            linked_question_ids?: string[];
            /** Linked Schedule Fields */
            linked_schedule_fields?: string[];
            deterministic_scoring?: components["schemas"]["DeterministicScoringGuide"] | null;
        };
        /** Criterion */
        "Criterion-Output": {
            /** Id */
            id: string;
            /** Section Id */
            section_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            criterion_type: components["schemas"]["CriterionType"];
            /** Weight */
            weight?: number | null;
            /** Min Cutoff */
            min_cutoff?: number | null;
            /** Max Score */
            max_score?: number | null;
            /** Evidence Checks */
            evidence_checks?: components["schemas"]["EvidenceCheck"][];
            /** Linked Question Ids */
            linked_question_ids?: string[];
            /** Linked Schedule Fields */
            linked_schedule_fields?: string[];
            deterministic_scoring?: components["schemas"]["DeterministicScoringGuide"] | null;
        };
        /**
         * CriterionType
         * @enum {string}
         */
        CriterionType: "mac" | "technical_cutoff_backed" | "technical_scored_only" | "commercial";
        /** DeterministicScoringGuide */
        DeterministicScoringGuide: {
            guide_type: components["schemas"]["DeterministicScoringType"];
            /** Answer Format */
            answer_format: string;
            /** Summary */
            summary: string;
            /** Rules */
            rules?: components["schemas"]["DeterministicScoringRule"][];
        };
        /** DeterministicScoringRule */
        DeterministicScoringRule: {
            /** Id */
            id: string;
            /** Condition */
            condition: string;
            /** Score */
            score?: number | null;
            /** Outcome */
            outcome?: ("pass" | "fail") | null;
        };
        /**
         * DeterministicScoringType
         * @enum {string}
         */
        DeterministicScoringType: "pass_fail" | "numeric_banded" | "discrete_banded";
        /** DownloadMetadata */
        DownloadMetadata: {
            /** File Name */
            file_name: string;
            /**
             * Content Type
             * @default application/json
             */
            content_type: string;
        };
        /** EvaluationReport */
        EvaluationReport: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            comparison_settings?: components["schemas"]["ComparisonSettings"] | null;
            /** Technical Results */
            technical_results?: components["schemas"]["TechnicalEvaluationResult"][];
            /** Commercial Results */
            commercial_results?: components["schemas"]["CommercialEvaluationResult"][];
            official_recommendation: components["schemas"]["AwardRecommendation"];
            /** Advisory Scenarios */
            advisory_scenarios?: components["schemas"]["ScenarioResult"][];
            /** Blocked Reasons */
            blocked_reasons?: string[];
        };
        /** EvidenceAnchor */
        EvidenceAnchor: {
            /** Id */
            id: string;
            /** Snippet */
            snippet: string;
            /** Locator */
            locator: string;
            /** Source Label */
            source_label?: string | null;
        };
        /** EvidenceCheck */
        EvidenceCheck: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
        };
        /** ExtractedField */
        ExtractedField: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Field Group */
            field_group: string;
            /** Question Id */
            question_id?: string | null;
            /** Schedule Id */
            schedule_id?: string | null;
            /** Schedule Column Id */
            schedule_column_id?: string | null;
            /** Criterion Ids */
            criterion_ids?: string[];
            /** Line Item Id */
            line_item_id?: string | null;
            state: components["schemas"]["ResponseState"];
            /** Raw Value */
            raw_value?: string | null;
            /** Normalized Hint */
            normalized_hint?: string | null;
            /** Quantity Value */
            quantity_value?: number | null;
            /** Numeric Value */
            numeric_value?: number | null;
            /** Currency */
            currency?: string | null;
            /** Uom */
            uom?: string | null;
            /** Notes */
            notes?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceAnchor"][];
        };
        /** FXRate */
        FXRate: {
            /** Currency */
            currency: string;
            /** Rate To Base */
            rate_to_base: number;
        };
        /** GeneralInfo */
        GeneralInfo: {
            /** Title */
            title: string;
            /** Rfq Code */
            rfq_code: string;
            /** Owner */
            owner: string;
            /** Region */
            region: string;
        };
        /** GovernanceInfo */
        GovernanceInfo: {
            /**
             * Official Award Basis
             * @default QCBS 70/30
             * @constant
             */
            official_award_basis: "QCBS 70/30";
            /** Technical Threshold Strategy */
            technical_threshold_strategy: string;
            /** Advisory Outputs */
            advisory_outputs: string[];
            /** Persistence Scope */
            persistence_scope: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LineItem */
        LineItem: {
            /** Id */
            id: string;
            /** Product Name */
            product_name: string;
            /** Category */
            category: string;
            /** Description */
            description: string;
            /** Hsn Sac */
            hsn_sac: string;
            /** Uom */
            uom: string;
        };
        /** LockedFrameworkArtifact */
        LockedFrameworkArtifact: {
            /**
             * Version
             * @default 1.0
             */
            version: string;
            /**
             * Locked At
             * Format: date-time
             */
            locked_at: string;
            rfq_snapshot: components["schemas"]["RFQDraft"];
            rubric_snapshot: components["schemas"]["RubricProposal-Output"];
            governance: components["schemas"]["GovernanceInfo"];
            download_metadata: components["schemas"]["DownloadMetadata"];
        };
        /** NormalizedField */
        NormalizedField: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Field Group */
            field_group: string;
            /** Criterion Ids */
            criterion_ids?: string[];
            /** Line Item Id */
            line_item_id?: string | null;
            /** Source Field Ids */
            source_field_ids?: string[];
            /** Normalized Value */
            normalized_value?: string | null;
            /** Quantity Value */
            quantity_value?: number | null;
            /** Numeric Value */
            numeric_value?: number | null;
            /** Currency */
            currency?: string | null;
            /** Base Currency Value */
            base_currency_value?: number | null;
            /** Uom */
            uom?: string | null;
            /** Target Uom */
            target_uom?: string | null;
            comparability_status: components["schemas"]["ComparabilityStatus"];
            /** Conversion Notes */
            conversion_notes?: string[];
            /** Blockers */
            blockers?: string[];
            /** Evidence Refs */
            evidence_refs?: string[];
        };
        /** NormalizedPricingLine */
        NormalizedPricingLine: {
            /** Line Item Id */
            line_item_id: string;
            /** Line Item Name */
            line_item_name: string;
            /** Quantity */
            quantity?: number | null;
            /** Uom */
            uom?: string | null;
            /** Target Uom */
            target_uom?: string | null;
            /** Currency */
            currency?: string | null;
            /** Total Price */
            total_price?: number | null;
            /** Base Currency Total */
            base_currency_total?: number | null;
            comparability_status: components["schemas"]["ComparabilityStatus"];
            /** Exclusions */
            exclusions?: string[];
            /** Source Field Ids */
            source_field_ids?: string[];
            /** Evidence Refs */
            evidence_refs?: string[];
            /** Conversion Notes */
            conversion_notes?: string[];
            /** Blockers */
            blockers?: string[];
        };
        /** Question */
        Question: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Purpose */
            purpose: string;
            /** Linked Criteria */
            linked_criteria?: string[];
        };
        /** RFQDraft */
        RFQDraft: {
            general_info: components["schemas"]["GeneralInfo"];
            /** Scope Overview */
            scope_overview: string;
            /** Timelines */
            timelines: components["schemas"]["TimelineItem"][];
            /** Buyer Priorities */
            buyer_priorities: components["schemas"]["BuyerPriority"][];
            /** Mandatory Conditions */
            mandatory_conditions: string[];
            /** Line Items */
            line_items: components["schemas"]["LineItem"][];
        };
        /** RawExtraction */
        RawExtraction: {
            /** Document Summary */
            document_summary: string;
            /** Question Answers */
            question_answers?: components["schemas"]["ExtractedField"][];
            /** Schedule Answers */
            schedule_answers?: components["schemas"]["ExtractedField"][];
            /** Technical Claims */
            technical_claims?: components["schemas"]["ExtractedField"][];
            /** Commercial Claims */
            commercial_claims?: components["schemas"]["ExtractedField"][];
            /** Warnings */
            warnings?: string[];
        };
        /** ResponseSchedule */
        ResponseSchedule: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Purpose */
            purpose: string;
            /** Columns */
            columns: components["schemas"]["ScheduleColumn"][];
            /** Linked Criteria */
            linked_criteria?: string[];
        };
        /**
         * ResponseState
         * @enum {string}
         */
        ResponseState: "answered" | "missing_vendor_response" | "missing_extractable_evidence" | "conflicting_evidence" | "not_applicable";
        /** RubricProposal */
        "RubricProposal-Input": {
            /** Sections */
            sections: components["schemas"]["RubricSection"][];
            /** Criteria */
            criteria: components["schemas"]["Criterion-Input"][];
            /** Aggregate Technical Threshold */
            aggregate_technical_threshold: number;
            /** Questions */
            questions: components["schemas"]["Question"][];
            /** Response Schedules */
            response_schedules: components["schemas"]["ResponseSchedule"][];
            /**
             * Official Award Basis
             * @default QCBS 70/30
             * @constant
             */
            official_award_basis: "QCBS 70/30";
            /** Generation Rationale */
            generation_rationale: string[];
        };
        /** RubricProposal */
        "RubricProposal-Output": {
            /** Sections */
            sections: components["schemas"]["RubricSection"][];
            /** Criteria */
            criteria: components["schemas"]["Criterion-Output"][];
            /** Aggregate Technical Threshold */
            aggregate_technical_threshold: number;
            /** Questions */
            questions: components["schemas"]["Question"][];
            /** Response Schedules */
            response_schedules: components["schemas"]["ResponseSchedule"][];
            /**
             * Official Award Basis
             * @default QCBS 70/30
             * @constant
             */
            official_award_basis: "QCBS 70/30";
            /** Generation Rationale */
            generation_rationale: string[];
        };
        /** RubricSection */
        RubricSection: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
        };
        /**
         * ScenarioKind
         * @enum {string}
         */
        ScenarioKind: "official_qcbs" | "advisory_lcs" | "advisory_qbs" | "advisory_ai";
        /** ScenarioRankingItem */
        ScenarioRankingItem: {
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name: string;
            /** Score */
            score?: number | null;
            /** Notes */
            notes?: string[];
        };
        /** ScenarioResult */
        ScenarioResult: {
            /** Scenario Name */
            scenario_name: string;
            scenario_kind: components["schemas"]["ScenarioKind"];
            /**
             * Is Official
             * @default false
             */
            is_official: boolean;
            /** Winner Vendor Id */
            winner_vendor_id?: string | null;
            /** Excluded Vendor Ids */
            excluded_vendor_ids?: string[];
            /** Weighting Or Rule Basis */
            weighting_or_rule_basis: string;
            /** Explanation */
            explanation: string;
            /** Evidence Refs */
            evidence_refs?: string[];
            /** Ranking */
            ranking?: components["schemas"]["ScenarioRankingItem"][];
        };
        /** ScheduleColumn */
        ScheduleColumn: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /**
             * Required
             * @default true
             */
            required: boolean;
        };
        /** SessionSnapshot */
        SessionSnapshot: {
            /** Session Id */
            session_id: string;
            status: components["schemas"]["SessionStatus"];
            rfq_draft: components["schemas"]["RFQDraft"];
            rubric_proposal?: components["schemas"]["RubricProposal-Output"] | null;
            locked_artifact?: components["schemas"]["LockedFrameworkArtifact"] | null;
            vendor_pack?: components["schemas"]["VendorPack"] | null;
            /** Vendors */
            vendors?: components["schemas"]["VendorRecord"][];
            comparison_settings?: components["schemas"]["ComparisonSettings"] | null;
            /** Vendor Reviews */
            vendor_reviews?: components["schemas"]["VendorReview"][];
            evaluation_report?: components["schemas"]["EvaluationReport"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "draft" | "proposal_ready" | "locked";
        /** TechnicalCriterionResult */
        TechnicalCriterionResult: {
            /** Criterion Id */
            criterion_id: string;
            /** Title */
            title: string;
            criterion_type: components["schemas"]["CriterionType"];
            status: components["schemas"]["TechnicalCriterionStatus"];
            /** Score */
            score?: number | null;
            /** Max Score */
            max_score?: number | null;
            /** Passed */
            passed?: boolean | null;
            /** Confidence */
            confidence?: number | null;
            /** Explanation */
            explanation: string;
            /** Evidence Refs */
            evidence_refs?: string[];
            /** Math Trace */
            math_trace?: string[];
            /** Risks */
            risks?: string[];
        };
        /**
         * TechnicalCriterionStatus
         * @enum {string}
         */
        TechnicalCriterionStatus: "passed" | "failed" | "scored" | "not_evaluated";
        /** TechnicalEvaluationResult */
        TechnicalEvaluationResult: {
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name: string;
            /** Passed Gate */
            passed_gate: boolean;
            /** Aggregate Score */
            aggregate_score: number;
            /** Threshold */
            threshold: number;
            /** Disqualification Reasons */
            disqualification_reasons?: string[];
            /** Criterion Results */
            criterion_results?: components["schemas"]["TechnicalCriterionResult"][];
            /** Summary */
            summary: string;
        };
        /** TimelineItem */
        TimelineItem: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Target Date */
            target_date: string;
            /** Description */
            description: string;
        };
        /** UomOverride */
        UomOverride: {
            /** From Uom */
            from_uom: string;
            /** To Uom */
            to_uom: string;
            /** Factor */
            factor: number;
            /** Line Item Id */
            line_item_id?: string | null;
        };
        /** UpdateVendorRequest */
        UpdateVendorRequest: {
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VendorDocument */
        VendorDocument: {
            /** File Name */
            file_name: string;
            /** Mime Type */
            mime_type: string;
            /** Extension */
            extension: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Warnings */
            warnings?: string[];
        };
        /** VendorPack */
        VendorPack: {
            /** Rfq Title */
            rfq_title: string;
            /**
             * Official Award Basis
             * @default QCBS 70/30
             * @constant
             */
            official_award_basis: "QCBS 70/30";
            /** Response Instructions */
            response_instructions?: string[];
            /** Questions */
            questions?: components["schemas"]["VendorPackQuestion"][];
            /** Response Schedules */
            response_schedules?: components["schemas"]["VendorPackSchedule"][];
            /** Criteria */
            criteria?: components["schemas"]["VendorPackCriterion"][];
        };
        /** VendorPackCriterion */
        VendorPackCriterion: {
            /** Criterion Id */
            criterion_id: string;
            /** Title */
            title: string;
            criterion_type: components["schemas"]["CriterionType"];
            /** Description */
            description: string;
            /** Linked Question Ids */
            linked_question_ids?: string[];
            /** Linked Schedule Fields */
            linked_schedule_fields?: string[];
        };
        /** VendorPackQuestion */
        VendorPackQuestion: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Purpose */
            purpose: string;
            /** Linked Criteria */
            linked_criteria?: string[];
        };
        /** VendorPackSchedule */
        VendorPackSchedule: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Purpose */
            purpose: string;
            /** Linked Criteria */
            linked_criteria?: string[];
            /** Columns */
            columns?: components["schemas"]["VendorPackScheduleField"][];
        };
        /** VendorPackScheduleField */
        VendorPackScheduleField: {
            /** Field Id */
            field_id: string;
            /** Schedule Id */
            schedule_id: string;
            /** Schedule Name */
            schedule_name: string;
            /** Column Id */
            column_id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /** Linked Criteria */
            linked_criteria?: string[];
        };
        /** VendorRecord */
        VendorRecord: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** @default no_document */
            status: components["schemas"]["VendorStatus"];
            document?: components["schemas"]["VendorDocument"] | null;
            /** Warnings */
            warnings?: string[];
            /** Extraction Error */
            extraction_error?: string | null;
            /** Last Extracted At */
            last_extracted_at?: string | null;
            /** Last Evaluated At */
            last_evaluated_at?: string | null;
        };
        /** VendorReview */
        VendorReview: {
            /** Vendor Id */
            vendor_id: string;
            document: components["schemas"]["VendorDocument"];
            /** Visual Fidelity Warning */
            visual_fidelity_warning?: string | null;
            raw_extraction: components["schemas"]["RawExtraction"];
            /** Normalized Fields */
            normalized_fields?: components["schemas"]["NormalizedField"][];
            /** Normalized Pricing */
            normalized_pricing?: components["schemas"]["NormalizedPricingLine"][];
            /** Warnings */
            warnings?: string[];
            /** Blockers */
            blockers?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** VendorScoreBreakdown */
        VendorScoreBreakdown: {
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name: string;
            /** Technical Score */
            technical_score?: number | null;
            /** Commercial Score */
            commercial_score?: number | null;
            /** Final Score */
            final_score?: number | null;
            /**
             * Passed Technical Gate
             * @default false
             */
            passed_technical_gate: boolean;
            /**
             * Commercially Comparable
             * @default false
             */
            commercially_comparable: boolean;
        };
        /**
         * VendorStatus
         * @enum {string}
         */
        VendorStatus: "no_document" | "uploaded" | "extracted" | "evaluation_ready" | "evaluated";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_rfq_sessions__session_id__rfq_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RFQDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_rubric_sessions__session_id__rubric_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_rubric_sessions__session_id__rubric_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RubricProposal-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_rubric_sessions__session_id__rubric_lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockedFrameworkArtifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_sessions__session_id__artifact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vendor_pack_sessions__session_id__vendor_pack_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorPack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_vendor_pack_sessions__session_id__vendor_pack_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vendor_sessions__session_id__vendors_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVendorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_vendor_sessions__session_id__vendors__vendor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                vendor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_vendor_sessions__session_id__vendors__vendor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                vendor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVendorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_vendor_document_sessions__session_id__vendors__vendor_id__document_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                vendor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_vendor_document_sessions__session_id__vendors__vendor_id__document_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_vendor_document_sessions__session_id__vendors__vendor_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                vendor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vendor_review_sessions__session_id__vendors__vendor_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                vendor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorReview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_comparison_settings_sessions__session_id__comparison_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_session_evaluation_sessions__session_id__evaluation_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_sessions__session_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
