import type { components } from "./generated";

export type AwardRecommendation = components["schemas"]["AwardRecommendation"];
export type AwardType = components["schemas"]["AwardType"];
export type BuyerPriority = components["schemas"]["BuyerPriority"];
export type CommercialEvaluationResult = components["schemas"]["CommercialEvaluationResult"];
export type CommercialLineItemResult = components["schemas"]["CommercialLineItemResult"];
export type ComparabilityStatus = components["schemas"]["ComparabilityStatus"];
export type ComparisonSettings = components["schemas"]["ComparisonSettings"];
export type Criterion = components["schemas"]["Criterion-Output"];
export type CriterionInput = components["schemas"]["Criterion-Input"];
export type CriterionType = components["schemas"]["CriterionType"];
export type DeterministicScoringGuide = components["schemas"]["DeterministicScoringGuide"];
export type DeterministicScoringRule = components["schemas"]["DeterministicScoringRule"];
export type DeterministicScoringType = components["schemas"]["DeterministicScoringType"];
export type DownloadMetadata = components["schemas"]["DownloadMetadata"];
export type EvidenceCheck = components["schemas"]["EvidenceCheck"];
export type EvidenceAnchor = components["schemas"]["EvidenceAnchor"];
export type EvaluationReport = components["schemas"]["EvaluationReport"];
export type ExtractedField = components["schemas"]["ExtractedField"];
export type FXRate = components["schemas"]["FXRate"];
export type GeneralInfo = components["schemas"]["GeneralInfo"];
export type GovernanceInfo = components["schemas"]["GovernanceInfo"];
export type LLMSettings = components["schemas"]["LLMSettings"];
export type LineItem = components["schemas"]["LineItem"];
export type LockedFrameworkArtifact = components["schemas"]["LockedFrameworkArtifact"];
export type NormalizedField = components["schemas"]["NormalizedField"];
export type NormalizedPricingLine = components["schemas"]["NormalizedPricingLine"];
export type Question = components["schemas"]["Question"];
export type RawExtraction = components["schemas"]["RawExtraction"];
export type ReasoningEffort = components["schemas"]["ReasoningEffort"];
export type ResponseState = components["schemas"]["ResponseState"];
export type ResponseSchedule = components["schemas"]["ResponseSchedule"];
export type RFQDraft = components["schemas"]["RFQDraft"];
export type RubricProposal = components["schemas"]["RubricProposal-Output"];
export type RubricProposalInput = components["schemas"]["RubricProposal-Input"];
export type RubricSection = components["schemas"]["RubricSection"];
export type ScheduleColumn = components["schemas"]["ScheduleColumn"];
export type ScenarioKind = components["schemas"]["ScenarioKind"];
export type ScenarioRankingItem = components["schemas"]["ScenarioRankingItem"];
export type ScenarioResult = components["schemas"]["ScenarioResult"];
export type SessionSnapshot = components["schemas"]["SessionSnapshot"];
export type SessionStatus = components["schemas"]["SessionStatus"];
export type TechnicalCriterionResult = components["schemas"]["TechnicalCriterionResult"];
export type TechnicalCriterionStatus = components["schemas"]["TechnicalCriterionStatus"];
export type TechnicalEvaluationResult = components["schemas"]["TechnicalEvaluationResult"];
export type RFQTimelineSet = components["schemas"]["RFQTimelineSet"];
export type UomOverride = components["schemas"]["UomOverride"];
export type VendorDocument = components["schemas"]["VendorDocument"];
export type VendorPack = components["schemas"]["VendorPack"];
export type VendorPackCriterion = components["schemas"]["VendorPackCriterion"];
export type VendorPackQuestion = components["schemas"]["VendorPackQuestion"];
export type VendorPackSchedule = components["schemas"]["VendorPackSchedule"];
export type VendorPackScheduleField = components["schemas"]["VendorPackScheduleField"];
export type VendorRecord = components["schemas"]["VendorRecord"];
export type VendorReview = components["schemas"]["VendorReview"];
export type VendorStatus = components["schemas"]["VendorStatus"];
export interface ValidationIssue {
  field: string;
  message: string;
}

export const OFFICIAL_AWARD_BASIS = "QCBS 70/30";
