export const SUPPORTED_RFQ_CURRENCIES = [
  "AUD",
  "BRL",
  "CAD",
  "CHF",
  "CNY",
  "CZK",
  "DKK",
  "EUR",
  "GBP",
  "HKD",
  "HUF",
  "IDR",
  "ILS",
  "INR",
  "ISK",
  "JPY",
  "KRW",
  "MXN",
  "MYR",
  "NOK",
  "NZD",
  "PHP",
  "PLN",
  "RON",
  "SEK",
  "SGD",
  "THB",
  "TRY",
  "USD",
  "ZAR",
] as const;

export const RFQ_UOM_OPTIONS = [
  { value: "Lot", label: "Lot", family: "Services" },
  { value: "Count", label: "Count", family: "Counts" },
  { value: "mg", label: "mg", family: "Weight" },
  { value: "g", label: "g", family: "Weight" },
  { value: "kg", label: "kg", family: "Weight" },
  { value: "mL", label: "mL", family: "Volume" },
  { value: "L", label: "L", family: "Volume" },
] as const;
